name: 'Avoid workflow being suspended'

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  auto_renew:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v2
      
      - name: 'Avoid Github Workflow being suspended'
        run: echo $(cat /proc/sys/kernel/random/uuid) > UUID.txt
      
      - name: 'Commit Files'
        id: commit
        run: |
          git config --local user.email "tuthanika@gmail.com"
          git config --local user.name "tuthanika"
          git add .
          git diff --quiet && git diff --staged --quiet || git commit -am 'avoid being suspended'
          echo ::set-output name=status::success
           
      - name: 'GitHub Push'
        if: steps.commit.output.status != 'success'
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ github.token }}
          branch: ${{ github.ref }}

      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 1
          keep_minimum_runs: 0
          delete_workflow_pattern: Avoid workflow being suspended
          
