# .github/workflows/scheduled-builds.yml
name: Ping Bot Okteto

on:
  workflow_dispatch:
  schedule:
    # Runs "at minute 55 past every hour" (see https://crontab.guru)
    - cron: '5 * * * *'
jobs:
  build:
    name: Ping Web
    runs-on: ubuntu-latest
    steps:
      - name: cURL request
        # Hit the webhook endpoint to rebuild  from the "main" branch
      # run: curl -X POST -d {} https://clonebot-tuthanika.cloud.okteto.net
        run: |
           curl -A "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:101.0) Gecko/20100101 Firefox/101.0" -v https://clonebot-tuthanika.cloud.okteto.net
           curl -A "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:101.0) Gecko/20100101 Firefox/101.0" -v https://app-80-tuthanika.cloud.okteto.net
           curl -A "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:101.0) Gecko/20100101 Firefox/101.0" -v https://app-81-tuthanika.cloud.okteto.net
           curl -A "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:101.0) Gecko/20100101 Firefox/101.0" -v https://app-8080-tuthanika.cloud.okteto.net
        
