name: Ping Index OneDrive

on:
  workflow_dispatch:
  schedule:
    - cron: '* 1 * * *'
    
jobs:
  build:
    name: Ping Web
    runs-on: ubuntu-latest
    steps:
      - name: cURL request
        # Hit the webhook endpoint to rebuild  from the "main" branch
      # run: curl -X POST -d {} url
        run: |
           curl -A "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:101.0) Gecko/20100101 Firefox/101.0" -v https://atp.vietstarhp.com
            
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 1
          keep_minimum_runs: 0
          delete_workflow_pattern: Ping Index OneDrive
        
